# action.yml
name: 'Spring Application Advisor'
description: 'Incrementally upgrade your Spring application dependencies'
inputs:
  artifactory_token:
    description: 'Token for Spring Enterprise Subscription'
    required: true
  app_advisor_server:
    description: 'URL endpoint for Spring Application Advisor'
    required: true
  git_token:
    description: 'Authentication token for generating pull requests against repo'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run App Advisor
      run: ${{ github.action_path }}/app-advisor.sh
      shell: bash
      env:
        ARTIFACTORY_TOKEN: ${{ inputs.artifactory_token }}
        APP_ADVISOR_SERVER: ${{ inputs.app_advisor_server }}
        GIT_TOKEN_FOR_PRS: ${{ inputs.git_token }}
