VERSION=1.1.2
curl -L -H "Authorization: Bearer eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJNUmo4OWVRNjkwSEE3eE40cXZvZ0FnajczSFJhdDNKcWcxanYyNDZHdTRnIn0.eyJzdWIiOiJqZnJ0QDAxZXA4M3F2MzFjcnowMHg2ZjZ6eWYwNHo2L3VzZXJzL2FuaWwtYW4ubmFpckBicm9hZGNvbS5jb20iLCJzY3AiOiJtZW1iZXItb2YtZ3JvdXBzOlROWi1TUFJJTkciLCJhdWQiOiJqZnJ0QDAxZXA4M3F2MzFjcnowMHg2ZjZ6eWYwNHo2IiwiaXNzIjoiamZydEAwMWVwODNxdjMxY3J6MDB4NmY2enlmMDR6Ni91c2Vycy9jc3AtdG9rZW4tZ3JhbnRvciIsImV4cCI6MTc1NDIzNjgxOCwiaWF0IjoxNzM4NTk4NDE4LCJqdGkiOiIyNTI3NjNlOS0zNGJjLTQ0MmUtYjUyMS03NWQ3MTFjNzRmMzEifQ.Vpzm6o56vd9STCdyo84Nj-XHQbGH2Sy6hKjtKRBsBxqX0LfAe84Mpe3yPLw-XaLtcxE8qZkK5LdfJerPRO8-3cs5kixq1EpAccLk0PlQ7KojTPiaS8anVwdwfBVAXUVAS78jBhUQgX72G6rkTxx-4TTjKbG2KqgzI28o8hdopyjFWgQlx8f15J_kQfP5kQXXKov8_slwxpS4ryBA7bLDSbQ2sjJos70118TPtI8n4g-W3pJ0ofxKrDqanSVa0TdHDUzfsJYnpS2rsuhLcbruYWPhhD4K8XNUz_6Kq8bjWDDT6Aw1CMMDeX3dsQ--SX1fyiKE2JJrd6Ed1Ax6TlEWPQ" -o /tmp/advisor-cli.tar -X GET https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/1.1.3/application-advisor-cli-linux-1.1.3.tar
tar -xf /tmp/advisor-cli.tar --strip-components=1 -C /tmp
install /tmp/advisor /usr/local/bin/advisor

advisor build-config get
advisor build-config publish --url=${APP_ADVISOR_SERVER}
advisor upgrade-plan get --url=${APP_ADVISOR_SERVER}
advisor upgrade-plan apply --push --url=${APP_ADVISOR_SERVER}
