name: spring-app-advisor-workflow
on:
  push:
    branches:
      - 'main'
jobs:
  cf_push_app_advisor_job:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Push Spring App to Cloud Foundry
    defaults:
      run:
        shell:
          bash
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'
      - name: CF Push
        uses: cpage-pivotal/cf-push-manifest-action@v8
        with:
          cf_api: <<ENTER VALUE>>
          cf_user: <<ENTER VALUE>>
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: <<ENTER VALUE>>
          cf_space: <<ENTER VALUE>>
      - name: Run Spring Application Advisor
        uses: cpage-pivotal/spring-app-advisor-action@v1.0.1
        with:
          artifactory_token: ${{ secrets.ArtifactoryToken }}
          git_token: ${{ secrets.GITHUB_TOKEN }}
          app_advisor_server: <<ENTER VALUE>>
